export const TITLE_CHANGE = 'TITLE_CHANGE';
export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';
export const ADD_ATTRIBUT = 'ADD_ATTRIBUT';
export const ADD_TYPE = 'ADD_TYPE';
export const ADD_GROUP = 'ADD_GROUP';

// STYLE
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const CHANGE_BACKGROUND_COLOR = 'CHANGE_BACKGROUND_COLOR';
export const CHANGE_BORDER_COLOR = 'CHANGE_BORDER_COLOR';
