// API
export const GET_NODES_SUCCESS = 'GET_NODES_SUCCESS';
export const GET_NODES_FAILED = 'GET_NODES_FAILED';
export const POST_NODE_SUCCESS = 'POST_NODE_SUCCESS';
export const POST_NODE_FAILED = 'POST_NODE_FAILED';
export const SHOW_NODE_SUCCESS = 'SHOW_NODE_SUCCESS';
export const SHOW_NODE_FAILED = 'SHOW_NODE_FAILED';
export const PUT_NODE_SUCCESS = 'PUT_NODE_SUCCESS';
export const PUT_NODE_FAILED = 'PUT_NODE_FAILED';
export const DELETE_NODE_SUCCESS = 'DELETE_NODE_SUCCESS';
export const DELETE_NODE_FAILED = 'DELETE_NODE_FAILED';
export const GET_ATTRIBUTE_DROPDOWN_SUCCESS = 'GET_ATTRIBUTE_DROPDOWN_SUCCESS';
export const GET_ATTRIBUTE_DROPDOWN_FAILED = 'GET_ATTRIBUTE_DROPDOWN_FAILED';
export const GET_GROUP_DROPDOWN_SUCCESS = 'GET_GROUP_DROPDOWN_SUCCESS';
export const GET_GROUP_DROPDOWN_FAILED = 'GET_GROUP_DROPDOWN_FAILED';

export const TITLE_CHANGE = 'TITLE_CHANGE';
export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';
export const ADD_ATTRIBUT = 'ADD_ATTRIBUT';
export const REMOVE_ATTRIBUT = 'REMOVE_ATTRIBUT';
export const ADD_GROUP = 'ADD_GROUP';

// STYLE
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const CHANGE_BACKGROUND_COLOR = 'CHANGE_BACKGROUND_COLOR';
export const CHANGE_BORDER_COLOR = 'CHANGE_BORDER_COLOR';
