// API
export const GET_WORKSPACES_LOADING = 'GET_WORKSPACES_LOADING';
export const GET_WORKSPACES_SUCCESS = 'GET_WORKSPACES_SUCCESS';
export const GET_WORKSPACES_FAILED = 'GET_WORKSPACES_FAILED';
export const POST_WORKSPACE_SUCCESS = 'POST_WORKSPACE_SUCCESS';
export const POST_WORKSPACE_FAILED = 'POST_WORKSPACE_FAILED';
export const SHOW_WORKSPACE_SUCCESS = 'SHOW_WORKSPACE_SUCCESS';
export const SHOW_WORKSPACE_FAILED = 'SHOW_WORKSPACE_FAILED';
export const PUT_WORKSPACE_SUCCESS = 'PUT_WORKSPACE_SUCCESS';
export const PUT_WORKSPACE_FAILED = 'PUT_WORKSPACE_FAILED';
export const DELETE_WORKSPACE_SUCCESS = 'DELETE_WORKSPACE_SUCCESS';
export const DELETE_WORKSPACE_FAILED = 'DELETE_WORKSPACE_FAILED';
export const GET_ATTRIBUTE_DROPDOWN_SUCCESS = 'GET_ATTRIBUTE_DROPDOWN_SUCCESS';
export const GET_ATTRIBUTE_DROPDOWN_FAILED = 'GET_ATTRIBUTE_DROPDOWN_FAILED';
export const GET_GROUP_DROPDOWN_SUCCESS = 'GET_GROUP_DROPDOWN_SUCCESS';
export const GET_GROUP_DROPDOWN_FAILED = 'GET_GROUP_DROPDOWN_FAILED';
export const GET_RELATIONSHIP_VALUES_SUCCESS = 'GET_RELATIONSHIP_VALUES_SUCCESS';
export const GET_RELATIONSHIP_VALUES_FAILED = 'GET_RELATIONSHIP_VALUES_FAILED';
export const GET_NODE_VALUES_SUCCESS = 'GET_NODE_VALUES_SUCCESS';
export const GET_NODE_VALUES_FAILED = 'GET_NODE_VALUES_FAILED';

export const GET_CVR_NODES_LOADING = 'GET_CVR_NODES_LOADING';
export const GET_CVR_NODES_SUCCESS = 'GET_CVR_NODES_SUCCESS';
export const GET_CVR_NODES_FAILED = 'GET_CVR_NODES_FAILED';
export const GET_WORKSPACE_NODE_COMPANY_DATA_LOADING = 'GET_WORKSPACE_NODE_COMPANY_DATA_LOADING';
export const GET_WORKSPACE_NODE_COMPANY_DATA_SUCCESS = 'GET_WORKSPACE_NODE_COMPANY_DATA_SUCCESS';
export const GET_WORKSPACE_NODE_COMPANY_DATA_FAILED = 'GET_WORKSPACE_NODE_COMPANY_DATA_FAILED';
export const GET_WORKSPACE_NODE_ADDRESS_INFO_LOADING = 'GET_WORKSPACE_NODE_ADDRESS_INFO_LOADING';
export const GET_WORKSPACE_NODE_ADDRESS_INFO_SUCCESS = 'GET_WORKSPACE_NODE_ADDRESS_INFO_SUCCESS';
export const GET_WORKSPACE_NODE_ADDRESS_INFO_FAILED = 'GET_WORKSPACE_NODE_ADDRESS_INFO_FAILED';


export const ANALYSE_OUTPUT_SUCCESS = 'ANALYSE_OUTPUT_SUCCESS';
export const ANALYSE_OUTPUT_FAILED = 'ANALYSE_OUTPUT_FAILED';


export const SAVE_WORKSPACE_SUCCESS = 'SAVE_WORKSPACE_SUCCESS';
export const SAVE_WORKSPACE_FAILED = 'SAVE_WORKSPACE_FAILED';

export const DELETE_WORKSPACE_ELEMENTS_SUCCESS = 'DELETE_WORKSPACE_ELEMENTS_SUCCESS';
export const DELETE_WORKSPACE_ELEMENTS_FAILED = 'DELETE_WORKSPACE_ELEMENTS_FAILED';

export const SHARE_WORKSPACE_SUCCESS = 'SHARE_WORKSPACE_SUCCESS';
export const SHARE_WORKSPACE_LOADING = 'SHARE_WORKSPACE_LOADING';
export const SHARE_WORKSPACE_FAILED = 'SHARE_WORKSPACE_FAILED';

export const PUBLIC_ACCESS_WORKSPACE_LOADING = 'PUBLIC_ACCESS_WORKSPACE_LOADING';
export const PUBLIC_ACCESS_WORKSPACE_SUCCESS = 'PUBLIC_ACCESS_WORKSPACE_SUCCESS';
export const PUBLIC_ACCESS_WORKSPACE_FAILED = 'PUBLIC_ACCESS_WORKSPACE_FAILED';

export const SET_PUBLIC_ACCESS_FALSE = 'SET_PUBLIC_ACCESS_FALSE';

// Workspcae Meta
export const LABEL_CHANGE = 'LABEL_CHANGE';
export const VALUES_CHANGE = 'VALUES_CHANGE';
export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';
export const ADD_GROUP = 'ADD_GROUP';
export const SHARE_ORG_CHANGE = 'SHARE_ORG_CHANGE';

// Edges
export const EDGE_ADD_TO_LIST = 'EDGE_ADD_TO_LIST';
export const POST_EDGE_LOADING = 'POST_EDGE_LOADING';
export const POST_EDGE_SUCCESS = 'POST_EDGE_SUCCESS';
export const POST_EDGE_FAILED = 'POST_EDGE_FAILED';
export const PUT_EDGE_LOADING = 'PUT_EDGE_LOADING';
export const PUT_EDGE_SUCCESS = 'PUT_EDGE_SUCCESS';
export const PUT_EDGE_FAILED = 'PUT_EDGE_FAILED';

// nodes
export const WORKSPACE_POST_NODE_LOADING = 'WORKSPACE_POST_NODE_LOADING';
export const WORKSPACE_POST_NODE_SUCCESS = 'WORKSPACE_POST_NODE_SUCCESS';
export const WORKSPACE_POST_NODE_FAILED = 'WORKSPACE_POST_NODE_FAILED';
export const WORKSPACE_PUT_NODE_LOADING = 'WORKSPACE_PUT_NODE_LOADING';
export const WORKSPACE_PUT_NODE_SUCCESS = 'WORKSPACE_PUT_NODE_SUCCESS';
export const WORKSPACE_PUT_NODE_FAILED = 'WORKSPACE_PUT_NODE_FAILED';
export const WORKSPACE_NODE_ADD_TO_LIST = 'WORKSPACE_NODE_ADD_TO_LIST';
export const WORKSPACE_NODE_ATTRIBUT_ADD_TO_LIST = 'WORKSPACE_NODE_ATTRIBUT_ADD_TO_LIST';

// anlysis
export const WORKSPACE_ANALYSIS_SAVE_SUCCESS = 'WORKSPACE_ANALYSIS_SAVE_SUCCESS';
export const WORKSPACE_ANALYSIS_SAVE_FAILED = 'WORKSPACE_ANALYSIS_SAVE_FAILED';
export const WORKSPACE_ANALYSIS_REVISION_SUCCESS = 'WORKSPACE_ANALYSIS_REVISION_SUCCESS';
export const WORKSPACE_ANALYSIS_REVISION_FAILED = 'WORKSPACE_ANALYSIS_REVISION_FAILED';


// CONTROL
export const SHOW_HANDLES_CHANGE = 'SHOW_HANDLES_CHANGE';


export const ANALYSIS_TEXT_CHANGE = 'ANALYSIS_TEXT_CHANGE';


export const SET_PUBLIC_VISITED = 'SET_PUBLIC_VISITED';

export const SET_SHOW_COMPANY_DATA = 'SET_SHOW_COMPANY_DATA';
export const SET_SHOW_ADDRESS_INFO = 'SET_SHOW_ADDRESS_INFO';


export const RUN_INTRO_WORKSPACE = 'RUN_INTRO_WORKSPACE';
export const CHANGE_STEP_INDEX_WORKSPACE = 'CHANGE_STEP_INDEX_WORKSPACE';

export const HANDLE_UNCERTAIN_COMPANIES = 'HANDLE_UNCERTAIN_COMPANIES';
