// API
export const GET_WORKSPACES_LOADING = 'GET_WORKSPACES_LOADING';
export const GET_WORKSPACES_SUCCESS = 'GET_WORKSPACES_SUCCESS';
export const GET_WORKSPACES_FAILED = 'GET_WORKSPACES_FAILED';
export const POST_WORKSPACE_SUCCESS = 'POST_WORKSPACE_SUCCESS';
export const POST_WORKSPACE_FAILED = 'POST_WORKSPACE_FAILED';
export const SHOW_WORKSPACE_SUCCESS = 'SHOW_WORKSPACE_SUCCESS';
export const SHOW_WORKSPACE_FAILED = 'SHOW_WORKSPACE_FAILED';
export const PUT_WORKSPACE_SUCCESS = 'PUT_WORKSPACE_SUCCESS';
export const PUT_WORKSPACE_FAILED = 'PUT_WORKSPACE_FAILED';
export const DELETE_WORKSPACE_SUCCESS = 'DELETE_WORKSPACE_SUCCESS';
export const DELETE_WORKSPACE_FAILED = 'DELETE_WORKSPACE_FAILED';
export const GET_ATTRIBUTE_DROPDOWN_SUCCESS = 'GET_ATTRIBUTE_DROPDOWN_SUCCESS';
export const GET_ATTRIBUTE_DROPDOWN_FAILED = 'GET_ATTRIBUTE_DROPDOWN_FAILED';
export const GET_GROUP_DROPDOWN_SUCCESS = 'GET_GROUP_DROPDOWN_SUCCESS';
export const GET_GROUP_DROPDOWN_FAILED = 'GET_GROUP_DROPDOWN_FAILED';
export const GET_RELATIONSHIP_VALUES_SUCCESS = 'GET_RELATIONSHIP_VALUES_SUCCESS';
export const GET_RELATIONSHIP_VALUES_FAILED = 'GET_RELATIONSHIP_VALUES_FAILED';
export const GET_NODE_VALUES_SUCCESS = 'GET_NODE_VALUES_SUCCESS';
export const GET_NODE_VALUES_FAILED = 'GET_NODE_VALUES_FAILED';
export const GET_ALERTS_SUCCESS = 'GET_ALERTS_SUCCESS';
export const GET_ALERTS_FAILED = 'GET_ALERTS_FAILED';


export const SAVE_WORKSPACE_SUCCESS = 'SAVE_WORKSPACE_SUCCESS';
export const SAVE_WORKSPACE_FAILED = 'SAVE_WORKSPACE_FAILED';

export const DELETE_WORKSPACE_ELEMENTS_SUCCESS = 'DELETE_WORKSPACE_ELEMENTS_SUCCESS';
export const DELETE_WORKSPACE_ELEMENTS_FAILED = 'DELETE_WORKSPACE_ELEMENTS_FAILED';

// Workspcae Meta
export const LABEL_CHANGE = 'LABEL_CHANGE';
export const VALUES_CHANGE = 'VALUES_CHANGE';
export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';
export const ADD_GROUP = 'ADD_GROUP';

// Edges
export const ADD_EDGE = 'ADD_EDGE';
export const POST_EDGE_LOADING = 'POST_EDGE_LOADING';
export const POST_EDGE_SUCCESS = 'POST_EDGE_SUCCESS';
export const POST_EDGE_FAILED = 'POST_EDGE_FAILED';
export const PUT_EDGE_LOADING = 'PUT_EDGE_LOADING';
export const PUT_EDGE_SUCCESS = 'PUT_EDGE_SUCCESS';
export const PUT_EDGE_FAILED = 'PUT_EDGE_FAILED';

// nodes
export const POST_NODE_LOADING = 'POST_NODE_LOADING';
export const POST_NODE_SUCCESS = 'POST_NODE_SUCCESS';
export const POST_NODE_FAILED = 'POST_NODE_FAILED';
export const PUT_NODE_LOADING = 'PUT_NODE_LOADING';
export const PUT_NODE_SUCCESS = 'PUT_NODE_SUCCESS';
export const PUT_NODE_FAILED = 'PUT_NODE_FAILED';


// CONTROL
export const SHOW_HANDLES_CHANGE = 'SHOW_HANDLES_CHANGE';
