export const STORE_ORGANIZATION_FAILED = 'STORE_ORGANIZATION_FAILED';

export const PURCHASE_FAILED = 'PURCHASE_FAILED';

export const DEMO_SUCCESS = 'DEMO_SUCCESS';
export const DEMO_FAILED = 'DEMO_FAILED';
