// API
export const GET_RELATIONSHIPS_SUCCESS = 'GET_RELATIONSHIPS_SUCCESS';
export const GET_RELATIONSHIPS_FAILED = 'GET_RELATIONSHIPS_FAILED';
export const POST_RELATIONSHIP_SUCCESS = 'POST_RELATIONSHIP_SUCCESS';
export const POST_RELATIONSHIP_FAILED = 'POST_RELATIONSHIP_FAILED';
export const SHOW_RELATIONSHIP_SUCCESS = 'SHOW_RELATIONSHIP_SUCCESS';
export const SHOW_RELATIONSHIP_FAILED = 'SHOW_RELATIONSHIP_FAILED';
export const PUT_RELATIONSHIP_SUCCESS = 'PUT_RELATIONSHIP_SUCCESS';
export const PUT_RELATIONSHIP_FAILED = 'PUT_RELATIONSHIP_FAILED';
export const DELETE_RELATIONSHIP_SUCCESS = 'DELETE_RELATIONSHIP_SUCCESS';
export const DELETE_RELATIONSHIP_FAILED = 'DELETE_RELATIONSHIP_FAILED';
export const GET_GROUP_DROPDOWN_SUCCESS = 'GET_GROUP_DROPDOWN_SUCCESS';
export const GET_GROUP_DROPDOWN_FAILED = 'GET_GROUP_DROPDOWN_FAILED';

export const LABEL_CHANGE = 'LABEL_CHANGE';
export const VALUES_CHANGE = 'VALUES_CHANGE';
export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';
export const ADD_GROUP = 'ADD_GROUP';

// STYLE
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const CHANGE_COLOR = 'CHANGE_COLOR';
