// API
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAILED = 'GET_GROUPS_FAILED';
export const POST_GROUP_SUCCESS = 'POST_GROUP_SUCCESS';
export const POST_GROUP_FAILED = 'POST_GROUP_FAILED';
export const SHOW_GROUP_SUCCESS = 'SHOW_GROUP_SUCCESS';
export const SHOW_GROUP_FAILED = 'SHOW_GROUP_FAILED';
export const PUT_GROUP_SUCCESS = 'PUT_GROUP_SUCCESS';
export const PUT_GROUP_FAILED = 'PUT_GROUP_FAILED';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILED = 'DELETE_GROUP_FAILED';


// OLD
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SHOW_DETAIL_PRODUCT = 'SHOW_DETAIL_PRODUCT';
export const TITLE_CHANGE = 'TITLE_CHANGE';
export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';
export const IMAGE_CHANGE = 'IMAGE_CHANGE';
