export const GET_ELEMET_COUNTS_SUCCESS = "GET_ELEMET_COUNTS_SUCCESS";
export const GET_ELEMET_COUNTS_FAILED = "GET_ELEMET_COUNTS_FAILED";

export const GET_TIMELINE_SUCCESS = "GET_TIMELINE_SUCCESS";
export const GET_TIMELINE_FAILED = "GET_TIMELINE_FAILED";

export const POST_FEATURE_SUCCESS = "POST_FEATURE_SUCCESS";
export const POST_FEATURE_FAILED = "POST_FEATURE_FAILED";

export const RUN_INTRO = "RUN_INTRO";
export const CHANGE_STEP_INDEX = "CHANGE_STEP_INDEX";
