// API
export const GET_ALERTS_SUCCESS = 'GET_ALERTS_SUCCESS';
export const GET_ALERTS_FAILED = 'GET_ALERTS_FAILED';
export const POST_ALERT_SUCCESS = 'POST_ALERT_SUCCESS';
export const POST_ALERT_FAILED = 'POST_ALERT_FAILED';
export const SHOW_ALERT_SUCCESS = 'SHOW_ALERT_SUCCESS';
export const SHOW_ALERT_FAILED = 'SHOW_ALERT_FAILED';
export const PUT_ALERT_SUCCESS = 'PUT_ALERT_SUCCESS';
export const PUT_ALERT_FAILED = 'PUT_ALERT_FAILED';
export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS';
export const DELETE_ALERT_FAILED = 'DELETE_ALERT_FAILED';
export const GET_GROUP_DROPDOWN_SUCCESS = 'GET_GROUP_DROPDOWN_SUCCESS';
export const GET_GROUP_DROPDOWN_FAILED = 'GET_GROUP_DROPDOWN_FAILED';
export const GET_CONDITION_DROPDOWN_SUCCESS = 'GET_CONDITION_DROPDOWN_SUCCESS';
export const GET_CONDITION_DROPDOWN_FAILED = 'GET_CONDITION_DROPDOWN_FAILED';

export const TITLE_CHANGE = 'TITLE_CHANGE';
export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';
export const ADD_GROUP = 'ADD_GROUP';
export const CHANGE_TAGS = 'CHANGE_TAGS';

export const ALERT_ADD_CONDITION = 'ADD_CONDITION';
export const ALERT_CHANGE_CONDITION = 'CHANGE_CONDITION';
export const ALERT_DELETE_CONDITION = 'DELETE_CONDITION';
