// API
export const GET_CONDITIONS_SUCCESS = 'GET_CONDITIONS_SUCCESS';
export const GET_CONDITIONS_FAILED = 'GET_CONDITIONS_FAILED';
export const POST_CONDITION_SUCCESS = 'POST_CONDITION_SUCCESS';
export const POST_CONDITION_FAILED = 'POST_CONDITION_FAILED';
export const GET_BUILD_TYPES_VALUES_SUCCESS = 'GET_BUILD_TYPES_VALUES_SUCCESS';
export const GET_BUILD_TYPES_VALUES_FAILED = 'GET_BUILD_TYPES_VALUES_FAILED';
export const SHOW_CONDITION_SUCCESS = 'SHOW_CONDITION_SUCCESS';
export const SHOW_CONDITION_FAILED = 'SHOW_CONDITION_FAILED';
export const PUT_CONDITION_SUCCESS = 'PUT_CONDITION_SUCCESS';
export const PUT_CONDITION_FAILED = 'PUT_CONDITION_FAILED';
export const DELETE_CONDITION_SUCCESS = 'DELETE_CONDITION_SUCCESS';
export const DELETE_CONDITION_FAILED = 'DELETE_CONDITION_FAILED';
export const GET_GROUP_DROPDOWN_SUCCESS = 'GET_GROUP_DROPDOWN_SUCCESS';
export const GET_GROUP_DROPDOWN_FAILED = 'GET_GROUP_DROPDOWN_FAILED';

export const SAVE_CONDITION_SUCCESS = 'SAVE_CONDITION_SUCCESS';
export const SAVE_CONDITION_FAILED = 'SAVE_CONDITION_FAILED';

export const DELETE_CONDITION_ELEMENTS_SUCCESS = 'DELETE_CONDITION_ELEMENTS_SUCCESS';
export const DELETE_CONDITION_ELEMENTS_FAILED = 'DELETE_CONDITION_ELEMENTS_FAILED';

export const GET_NODE_VALUES_SUCCESS = 'GET_NODE_VALUES_SUCCESS';
export const GET_NODE_VALUES_FAILED = 'GET_NODE_VALUES_FAILED';
export const GET_RELATIONSHIP_VALUES_SUCCESS = 'GET_RELATIONSHIP_VALUES_SUCCESS';
export const GET_RELATIONSHIP_VALUES_FAILED = 'GET_RELATIONSHIP_VALUES_FAILED';
export const POST_NODE_SUCCESS = 'POST_NODE_SUCCESS';
export const POST_NODE_FAILED = 'POST_NODE_FAILED';
export const PUT_NODE_SUCCESS = 'PUT_NODE_SUCCESS';
export const PUT_NODE_FAILED = 'PUT_NODE_FAILED';

export const PUT_EDGE_SUCCESS = 'PUT_EDGE_SUCCESS';
export const PUT_EDGE_FAILED = 'PUT_EDGE_FAILED';


export const POST_EDGE_SUCCESS = 'POST_EDGE_SUCCESS';
export const POST_EDGE_FAILED = 'POST_EDGE_FAILED';


export const TITLE_CHANGE = 'TITLE_CHANGE';
export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';
export const ADD_GROUP = 'ADD_GROUP';
export const CHANGE_CONDITION_ROW = 'CHANGE_CONDITION_ROW';
