// API
export const GET_CONDITIONS_SUCCESS = 'GET_CONDITIONS_SUCCESS';
export const GET_CONDITIONS_FAILED = 'GET_CONDITIONS_FAILED';
export const POST_CONDITION_SUCCESS = 'POST_CONDITION_SUCCESS';
export const POST_CONDITION_FAILED = 'POST_CONDITION_FAILED';
export const GET_BUILD_TYPES_VALUES_SUCCESS = 'GET_BUILD_TYPES_VALUES_SUCCESS';
export const GET_BUILD_TYPES_VALUES_FAILED = 'GET_BUILD_TYPES_VALUES_FAILED';
export const SHOW_CONDITION_SUCCESS = 'SHOW_CONDITION_SUCCESS';
export const SHOW_CONDITION_FAILED = 'SHOW_CONDITION_FAILED';
export const PUT_CONDITION_SUCCESS = 'PUT_CONDITION_SUCCESS';
export const PUT_CONDITION_FAILED = 'PUT_CONDITION_FAILED';
export const DELETE_CONDITION_SUCCESS = 'DELETE_CONDITION_SUCCESS';
export const DELETE_CONDITION_FAILED = 'DELETE_CONDITION_FAILED';
export const GET_GROUP_DROPDOWN_SUCCESS = 'GET_GROUP_DROPDOWN_SUCCESS';
export const GET_GROUP_DROPDOWN_FAILED = 'GET_GROUP_DROPDOWN_FAILED';

export const TITLE_CHANGE = 'TITLE_CHANGE';
export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';
export const ADD_GROUP = 'ADD_GROUP';
export const ADD_TYPE = 'ADD_TYPE';
export const ADD_CONDITION_ROW = 'ADD_CONDITION_ROW';
